project:
  type: website
  output-dir: docs

website:
  title: "Market Research"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: reports.qmd  # Changed this line
        text: Reports
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true