project:
  type: website
  output-dir: docs
  post-render: scripts/post_rename.py

website:
  title: "Market Research"
  # favicon: assets/favicon.ico
  # site-url: https://yourusername.github.io/yourrepo/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Reports
        menu:
          - href: report-latest.html
            text: Latest Report
          - href: archive/
            text: Archive
      - href: about.qmd
        text: About
  sidebar:
    style: "floating"
    search: true

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
